name: tabrel
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - matplotlib
  - lightgbm
  - numpy==1.26.4
  - scikit-learn
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit
  - geopandas
  - plotly
  - pycirclize
  - pytest
  - pytest-cov
  - mypy
  - black
  - flake8
  - jupyter
  - seaborn
  - kagglehub
  - pip
  - pip:
    - pre-commit
    - rtdl-num-embeddings
    - torch_geometric
    - kaleido
