name: tabrel
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - matplotlib
  - scikit-learn
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit
  - pytest
  - pytest-cov
  - mypy
  - black
  - flake8
  - jupyter
  - pip
  - pip:
    - pre-commit
