name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Set up Micromamba
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: environment.yml
        cache-environment: true
        post-cleanup: 'all'
    - name: Static analysis with mypy
      run: micromamba run -n tabrel python -m mypy src/
    - name: Run tests with coverage
      run: |
        micromamba run -n tabrel pytest \
          --cov=src/tabrel \
          --cov-report=xml \
          --cov-report=term \
          test/ -v
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
